# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

# GitHub Actions 워크플로우의 이름
name: Java CI with Gradle

# 워크플로우를 언제 실행할지에 대한 정의
on:
  pull_request:
    branches: [ "main" ] # 'main' 브랜치에 pull request가 열릴 때

# 워크플로우에서 사용할 권한 설정
permissions:
  contents: read

# 워크플로우의 작업 정의
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # MySQL 설정
      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'ourisland'   # MySQL 데이터베이스의 스키마명 설정
          mysql user: ${{ secrets.MYSQL_USERNAME }}
          mysql password: ${{ secrets.MYSQL_PASSWORD }}

      # application.yml 파일을 실행 가능하게 만들기
      - name: make application.yml
        run:
          touch ./src/main/resources/application.yml
        shell: bash

      # 시크릿 값으로 application.yml 파일 생성
      - name: deliver application
        run: echo "${{ secrets.APPLICATION_DEV }}" > ./src/main/resources/application.yml
        shell: bash

      # 환경 변수 출력
      - name: print env
        run: echo "${{ secrets.OCCUPY_SECRET }}"

#      # 비밀 정보 복사
#      - name: Copy Secret
#        env:
#          OCCUPY_SECRETS: ${{ secrets.OCCUPY_SECRET }}
##          OCCUPY_DEV_SECRETS: ${{ secrets.OCCUPY_DEV_SECRET }}
#          OCCUPY_SECRET_DIR: src/main/resources
#          OCCUPY_SECRET_FILE: application.yml
##          OCCUPY_SECRET_DEV_FILE: application-dev.yml
#        run: |
#          echo $OCCUPY_SECRETS | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_FILE &&
##          echo $OCCUPY_DEV_SECRET | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DEV_FILE



      # Gradlew 실행 권한 설정
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
        working-directory: ./back-end # gradlew 파일이 있는 디렉토리로 이동


      # Gradle로 빌드
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      # Unit 테스트 결과 게시
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: build/test-results/test/**/*.xml
